// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_K4Y8wAVUq6unc_fnsaJAdbneaF2_Ao',
    appId: '1:409853825637:web:67c9a2d6d8c5d31d1c2c8c',
    messagingSenderId: '409853825637',
    projectId: 'lista-de-tarefa-76e3c',
    authDomain: 'lista-de-tarefa-76e3c.firebaseapp.com',
    storageBucket: 'lista-de-tarefa-76e3c.firebasestorage.app',
    measurementId: 'G-RL5ZG8TKZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hQ4FBcl2INsCvnoZSMlAOk6wWljBuyU',
    appId: '1:409853825637:android:97a8888df06816a01c2c8c',
    messagingSenderId: '409853825637',
    projectId: 'lista-de-tarefa-76e3c',
    storageBucket: 'lista-de-tarefa-76e3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWsp7SorS-8xurAu0ATO60gfeIlg8qfT8',
    appId: '1:409853825637:ios:d2f0165ae7ffb8a51c2c8c',
    messagingSenderId: '409853825637',
    projectId: 'lista-de-tarefa-76e3c',
    storageBucket: 'lista-de-tarefa-76e3c.firebasestorage.app',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWsp7SorS-8xurAu0ATO60gfeIlg8qfT8',
    appId: '1:409853825637:ios:d2f0165ae7ffb8a51c2c8c',
    messagingSenderId: '409853825637',
    projectId: 'lista-de-tarefa-76e3c',
    storageBucket: 'lista-de-tarefa-76e3c.firebasestorage.app',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7_K4Y8wAVUq6unc_fnsaJAdbneaF2_Ao',
    appId: '1:409853825637:web:697b42efb990fb521c2c8c',
    messagingSenderId: '409853825637',
    projectId: 'lista-de-tarefa-76e3c',
    authDomain: 'lista-de-tarefa-76e3c.firebaseapp.com',
    storageBucket: 'lista-de-tarefa-76e3c.firebasestorage.app',
    measurementId: 'G-1XKZWYKXD5',
  );
}
